version: '3'
services:
  python:
    # image: python:3.7.3
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_NAME
    command:
      python manage.py runserver